### ISSUE TITLE
Plot Function Updates

### ISSUE THREAD

**Issue by jsleslie** [UBC-MDS/DSCI532_Group215_ParticulatesMatter_R#10]
Hey guys, I wanted to itemize the plot function updates we talked about earlier:

1. Remove the titles
2. Reverse color scale on heatmap 
3. Fix heatmap date scale - show years only or remove completely

**Comment by KarlosMuradyan** [comment]
The 3. point is solved with pull request #15

**Comment by tejasph** [comment]
All requests have been dealt with.
